name: dslink_schedule
version: 0.0.7
description: Schedule DSLink
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
  http: ">=0.11.2 <0.12.0"
  timezone: "^0.5.0-dev-2"
  package_config: "^1.0.0"
  xml: "^2.4.0"
